name: amar_daktar
description: A new Flutter application.
version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.6+1
  toast: ^0.1.5
  progress_dialog: ^1.2.0
  image_picker:
  fluttertoast: ^3.1.3
  connectivity: ^0.4.6+2
  provider: ^4.0.3
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
